// constants
export const SEARCH_LOCATION = "SEARCH_LOCATION";
export const CHANGE_LOCATION_INFO = "CHANGE_LOCATION_INFO";
export const GET_ALL_TYPE = "GET_ALL_TYPE";
export const CREATE_LOCAION = "CREATE_LOCAION";
export const GET_ALL_LOCATION = "GET_ALL_LOCATION";
export const GET_LOCATION_DETAIL = "GET_LOCATION_DETAIL";
export const CHANGE_MARKER_POSITION = "CHANGE_MARKER_POSITION";
export const CREATE_TYPE = "CREATE_TYPE";
export const EDIT_TYPE = "EDIT_TYPE";
export const EDIT_LOCATION = "EDIT_LOCATION";
export const GET_LIST_TOUR = "GET_LIST_TOUR";
export const GET_TOUR_BY_ID = "GET_TOUR_BY_ID";
export const GET_LIST_TOUR_TURN = "GET_LIST_TOUR_TURN";
export const GET_TOUR_TURN_BY_ID = "GET_TOUR_TURN_BY_ID";
export const CREATE_TOUR_TURN = "CREATE_TOUR_TURN";
export const EDIT_TOUR_TURN = "EDIT_TOUR_TURN";
export const GET_LIST_ROUTE = "GET_LIST_ROUTE";
export const GET_ROUTE_BY_ID = "GET_ROUTE_BY_ID";
export const CREATE_ROUTE = "CREATE_ROUTE";
export const EDIT_ROUTE = "EDIT_ROUTE";
export const CREATE_TOUR = "CREATE_TOUR";
export const EDIT_TOUR = "EDIT_TOUR";
export const GET_LIST_TRANSPORT = "GET_LIST_TRANSPORT";
export const CREATE_TRANSPORT = "CREATE_TRANSPORT";
export const GET_TRANSPORT_BY_ID = "GET_TRANSPORT_BY_ID";
export const EDIT_TRANSPORT = "EDIT_TRANSPORT";
export const GET_LIST_USER = "GET_LIST_USER";


