export const policy = `Giá tour bao gồm:
- Xe tham quan (16, 29, 35, 45 chỗ tùy theo số lượng khách) theo chương trình:....
- Vé máy bay khứ hồi: .....
- Hành lý: .....
- Khách sạn theo tiêu chuẩn: .....
- Các bữa ăn theo chương trình: ...
- Vé tham quan theo chương trình: ....
- Hướng dẫn viên tiếng Việt nối tuyến
- Bảo hiểm với mức bồi thường: .....
- Quà tặng: Nón Traveltuorist, nước suối, khanh lạnh.....
- Thuế VAT. 
Giá tour không bao gồm:
- Chi phí cá nhân: .....
- Chi phí tham quan ngoài chương trình: ......`;
